config/routes.rb
Rails.application.routes.draw do
  resources :buyers do
    resources :offers
  end
  resources :listings, only: :index
  resources :vendors do
    resources :offers, except: [:destroy, :new, :create]
    resources :listings do
      resources :offers, only: [:index, :show]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'listings#index'
end

app/models/listing.rb
require 'action_view'
include ActionView::Helpers::DateHelper

class Listing < ApplicationRecord
  belongs_to :vendor
  has_many :offers
  has_many :buyers, through: :offers
  validates :quantity, presence: true, :numericality =>  {:greater_than => 0}

  def has_accepted_offer?
    offers.where(accepted: true).exists?
  end

  def expired?
    time_elapsed >= 7*24*60*60
  end

  def time_elapsed
    Time.now.utc - created_at
  end

  def time_remaining
    distance_of_time_in_words(7*24*60*60 - time_elapsed)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_vendor
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :set_offers, only: :show
  # GET /listings
  # GET /listings.json

  def index
    if @vendor.nil?
      @current_listings = Listing.where(:created_at => (Date.today - 7.days)..Date.today).order('created_at asc')
      @expired_listings = Listing.where.not(:created_at => (Date.today - 7.days)..Date.today)
      @listings = @current_listings + @expired_listings
    else
      @listings = @vendor.listings
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = @vendor.listings.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = @vendor.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to vendor_listing_path(@vendor, @listing), notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    # binding.pry
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to vendor_listing_path(@vendor, @listing), notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_vendor
    p "In set vendor"
    p params[:vendor_id]
    @vendor = Vendor.find_by(id: params[:vendor_id])
    p "After vendor set"
    p @vendor
  end

  def set_listing
    p "In set listing"
      @listing = @vendor.listings.find(params[:id])
  end

  def set_offers
    @offers = Offer.where(listing_id: @listing.id)
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:vendor_id, :quantity, :species, buyer_ids: [])
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for([@vendor, @listing]) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Vendor: <%= @vendor.name %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :species %>
    <%= f.text_field :species %>
  </div>

  <div class="field">
    <% hidden_field_tag "listing[buyer_ids][]", nil %>
    <% Buyer.all.each do |buyer| %>
      <%= check_box_tag "listing[buyer_ids][]", buyer.id,
        listing.buyer_ids.include?(buyer.id), id: dom_id(buyer) %>
      <%= label_tag dom_id(buyer), buyer.name %> <br>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', vendor_listing_path(@vendor, @listing) %> |
<%= link_to 'Back', vendor_listings_path(@vendor) %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Vendor</th>
      <th>Quantity</th>
      <th>Species</th>
      <th>Time Remaining</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.vendor.name  %></td>
        <td><%= listing.quantity %></td>
        <td><%= listing.species %></td>
        <td><%= listing.expired? ? "Listing expired" : listing.time_remaining %> </td>
        <td><%= link_to 'Show', vendor_listing_path(listing.vendor_id, listing) %></td>
        <td><%= link_to 'Edit', edit_vendor_listing_path(listing.vendor_id, listing) %></td>
        <td><%= button_to 'Destroy', vendor_listing_path(listing.vendor_id, listing), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @vendor %>
<%= link_to 'New Listing', new_vendor_listing_path(@vendor) %>
<% end %>
<%= link_to 'View Vendors', vendors_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', vendor_listings_path(@vendor) %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<% if @listing.expired? %>
  <h4>This listing has expired. No more offers can be made.</h4>
<% else %>
  <h4> Time remaining: <%= @listing.time_remaining %> </h4>
<% end %>

<p>
  <strong>Vendor:</strong>
  <%= @listing.vendor.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @listing.quantity %>
</p>

<p>
  <strong>Species:</strong>
  <%= @listing.species %>
</p>

<p>
  <strong>Potential buyers:</strong>
  <ul>
    <% @listing.buyers.each do |buyer| %>
        <li><%= buyer.name %> </li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Offers:</strong>

  <table>
    <thead>
      <tr>
        <th>Buyer</th>
        <th>Amount</th>
        <th>Accepted</th>
        <% unless @listing.has_accepted_offer? %>
          <th>Accept</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @listing.offers.each do |offer| %>
        <tr>
          <td><%= offer.buyer.name %></td>
          <td><%= offer.amount %></td>
          <td><%= offer.accepted ? 'Yes' : 'No' %></td>
          <% unless @listing.has_accepted_offer? %>
            <td>
              <%= link_to 'Accept', vendor_offer_path(offer.vendor, offer, { 'offer[accepted]'=> true}), method: :put, data: { confirm: 'Are you sure you want to accept this offer?'} %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<%= link_to 'Edit', edit_vendor_listing_path(@vendor, @listing) %> |
<%= link_to 'Back', vendor_listings_path(@vendor) %>