config/routes.rb
Rails.application.routes.draw do
  resources :buyers do
    resources :offers
  end
  resources :listings, only: :index
  resources :vendors do
    resources :offers, except: [:destroy, :new, :create]
    resources :listings do
      resources :offers, only: [:index, :show]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'listings#index'
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :buyer
  belongs_to :listing

  def vendor
    listing.vendor
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_buyer
  before_action :set_vendor
  before_action :set_listing
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    if @buyer
      @offers = @buyer.offers
    elsif @listing
      @offers = @listing.offers
    elsif @vendor
      @offers = @vendor.offers
    else
      @offers = Offer.all
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = @buyer.offers.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to vendor_offer_path(@vendor, @offer), notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: vendor_offer_path(@vendor, @offer) }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to :back, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: vendor_offer_path(@vendor, @offer) }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to vendor_offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    def set_buyer
      @buyer = Buyer.find_by(id: params[:buyer_id])
    end

    def set_vendor
      @vendor = Vendor.find_by(id: params[:vendor_id])
    end

    def set_listing
      @listing = Listing.find_by(id: params[:listing_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:buyer_id, :listing_id, :amount, :accepted)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for([@buyer, @offer]) do |f| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :buyer_id %>:
    <%= @buyer.name %>
  </div>

  <div class="field">
    <%= f.label :listing_id %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offers</h1>

<table>
  <thead>
    <tr>
      <% if @buyer %>
        <th>Vendor</th>
      <% else %>
        <th>Buyer</th>
      <% end %>
      <th>Listing</th>
      <th>Amount</th>
      <th>Accepted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <% if @buyer %>
          <td><%= offer.vendor.name %></td>
      <% else %>
          <td><%= offer.buyer.name %></td>
      <% end %>
        <td><%= offer.listing.quantity.to_s + " " + offer.listing.species %></td>
        <td><%= offer.amount %></td>
        <td><%= offer.accepted ? "Yes" : "No" %></td>
        <td><%= link_to 'Show', buyer_offer_path(offer.buyer_id, offer) %></td>
        <td><%= link_to 'Edit', edit_buyer_offer_path(offer.buyer_id, offer) %></td>
        <td><%= link_to 'Destroy', buyer_offer_path(offer.buyer_id, offer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Back', buyer_offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Buyer:</strong>
  <%= @offer.buyer %>
</p>

<p>
  <strong>Listing:</strong>
  <%= @offer.listing %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @offer.amount %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @offer.accepted ? "Yes" : "No" %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>