config/routes.rb
Rails.application.routes.draw do
  resources :buyers do
    resources :offers
  end
  resources :listings, only: :index
  resources :vendors do
    resources :offers, except: [:destroy, :new, :create]
    resources :listings do
      resources :offers, only: [:index, :show]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'listings#index'
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  has_many :offers
  has_many :listings, through: :offers
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show, :edit, :update, :destroy]

  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to @buyer, notice: 'Buyer was successfully created.' }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1
  # PATCH/PUT /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer.destroy
    respond_to do |format|
      format.html { redirect_to buyers_url, notice: 'Buyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:name)
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_form.html.erb
<%= form_for(buyer) do |f| %>
  <% if buyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

      <ul>
      <% buyer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buyers/edit.html.erb
<h1>Editing Buyer</h1>

<%= render 'form', buyer: @buyer %>

<%= link_to 'Show', @buyer %> |
<%= link_to 'Back', buyers_path %>

app/views/buyers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buyers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buyers.each do |buyer| %>
      <tr>
        <td><%= buyer.name %></td>
        <td><%= link_to 'Show', buyer %></td>
        <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
        <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buyer', new_buyer_path %>

app/views/buyers/new.html.erb
<h1>New Buyer</h1>

<%= render 'form', buyer: @buyer %>

<%= link_to 'Back', buyers_path %>

app/views/buyers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @buyer.name %>
</p>
<%= link_to 'View Offers', buyer_offers_path(@buyer, @offer) %> |
<%= link_to 'Edit', edit_buyer_path(@buyer) %> |
<%= link_to 'Back', buyers_path %>